#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS7raZReCuCV1MCnVvqSvPoMxtQtTw4k5hoK"
APP_SECRET: "7S8gRcTOfeLFwjdvDu8Ixi1KFZWsDgc9z4qeX/LKBKJqMHZYt5EFzhbRv0NoND1NgdLi0QJgKZjHSLq9FOOinQEzgItfI71p+7v+Jz1bsDmk9AFSD8kEy9VhDiXEoLigm6z3HlBeROZcisM5rMQVohakwuKYfrQsqcZHR3thfj40AozPXGY="

#계좌번호 앞 8자리
CANO: "68359806"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1191729116140023930/zOpOlHETh4At39xft02RmbG1xO40VH70DLjoXsrxUixLB7KZQ6JyG7JVPFY4362ynJq6"